export interface User {
	idUsuario?: number,
	dataCadastro: Date | null,
	nome: string,
	email: string,
	tipoUsuario: number | null,
	cc: string,
	ddd: number | null,
	telefone: string,
	ativo: boolean,
	documentoContribuinte: string,
	logradouro: string,
	numeroEndereco: string,
	cep: string,
	cidade: string,
	bairro: string,
	uf: string,
	complementoEndereco: string,
	logradouroEnderecoAdicional: string,
	numeroEnderecoAdicional: string,
	cepEnderecoAdicional: string,
	cidadeEnderecoAdicional: string,
	ufEnderecoAdicional: string,
	bairroEnderecoAdicional: string,
	complementoEnderecoAdicional: string
  }