export const countries = [
	{ name: 'Afeganistão', code: 'af', dialCode: '93' },
	{ name: 'África do Sul', code: 'za', dialCode: '27' },
	{ name: 'Albânia', code: 'al', dialCode: '355' },
	{ name: 'Alemanha', code: 'de', dialCode: '49' },
	{ name: 'Andorra', code: 'ad', dialCode: '376' },
	{ name: 'Angola', code: 'ao', dialCode: '244' },
	{ name: 'Antígua e Barbuda', code: 'ag', dialCode: '1-268' },
	{ name: 'Arábia Saudita', code: 'sa', dialCode: '966' },
	{ name: 'Argélia', code: 'dz', dialCode: '213' },
	{ name: 'Argentina', code: 'ar', dialCode: '54' },
	{ name: 'Armênia', code: 'am', dialCode: '374' },
	{ name: 'Austrália', code: 'au', dialCode: '61' },
	{ name: 'Áustria', code: 'at', dialCode: '43' },
	{ name: 'Azerbaijão', code: 'az', dialCode: '994' },
	{ name: 'Bahamas', code: 'bs', dialCode: '1-242' },
	{ name: 'Bahrein', code: 'bh', dialCode: '973' },
	{ name: 'Bangladesh', code: 'bd', dialCode: '880' },
	{ name: 'Barbados', code: 'bb', dialCode: '1-246' },
	{ name: 'Bélgica', code: 'be', dialCode: '32' },
	{ name: 'Belize', code: 'bz', dialCode: '501' },
	{ name: 'Benim', code: 'bj', dialCode: '229' },
	{ name: 'Bermudas', code: 'bm', dialCode: '1-441' },
	{ name: 'Bielorrússia', code: 'by', dialCode: '375' },
	{ name: 'Bolívia', code: 'bo', dialCode: '591' },
	{ name: 'Bósnia e Herzegovina', code: 'ba', dialCode: '387' },
	{ name: 'Botsuana', code: 'bw', dialCode: '267' },
	{ name: 'Brasil', code: 'br', dialCode: '55' },
	{ name: 'Brunei', code: 'bn', dialCode: '673' },
	{ name: 'Bulgária', code: 'bg', dialCode: '359' },
	{ name: 'Burkina Faso', code: 'bf', dialCode: '226' },
	{ name: 'Burundi', code: 'bi', dialCode: '257' },
	{ name: 'Butão', code: 'bt', dialCode: '975' },
	{ name: 'Cabo Verde', code: 'cv', dialCode: '238' },
	{ name: 'Camarões', code: 'cm', dialCode: '237' },
	{ name: 'Camboja', code: 'kh', dialCode: '855' },
	{ name: 'Canadá', code: 'ca', dialCode: '1' },
	{ name: 'Catar', code: 'qa', dialCode: '974' },
	{ name: 'Cazaquistão', code: 'kz', dialCode: '7' },
	{ name: 'Chade', code: 'td', dialCode: '235' },
	{ name: 'Chile', code: 'cl', dialCode: '56' },
	{ name: 'China', code: 'cn', dialCode: '86' },
	{ name: 'Chipre', code: 'cy', dialCode: '357' },
	{ name: 'Colômbia', code: 'co', dialCode: '57' },
	{ name: 'Comores', code: 'km', dialCode: '269' },
	{ name: 'Congo', code: 'cg', dialCode: '242' },
	{ name: 'Congo (Rep. Dem. do)', code: 'cd', dialCode: '243' },
	{ name: 'Coreia do Norte', code: 'kp', dialCode: '850' },
	{ name: 'Coreia do Sul', code: 'kr', dialCode: '82' },
	{ name: 'Costa Rica', code: 'cr', dialCode: '506' },
	{ name: 'Croácia', code: 'hr', dialCode: '385' },
	{ name: 'Cuba', code: 'cu', dialCode: '53' },
	{ name: 'Chipre', code: 'cy', dialCode: '357' },
	{ name: 'República Checa', code: 'cz', dialCode: '420' },
	{ name: 'Dinamarca', code: 'dk', dialCode: '45' },
	{ name: 'Djibuti', code: 'dj', dialCode: '253' },
	{ name: 'Dominica', code: 'dm', dialCode: '1-767' },
	{ name: 'Egito', code: 'eg', dialCode: '20' },
	{ name: 'El Salvador', code: 'sv', dialCode: '503' },
	{ name: 'Emirados Árabes Unidos', code: 'ae', dialCode: '971' },
	{ name: 'Equador', code: 'ec', dialCode: '593' },
	{ name: 'Eritreia', code: 'er', dialCode: '291' },
	{ name: 'Eswatini', code: 'sz', dialCode: '268' },
	{ name: 'Eslováquia', code: 'sk', dialCode: '421' },
	{ name: 'Eslovênia', code: 'si', dialCode: '386' },
	{ name: 'Espanha', code: 'es', dialCode: '34' },
	{ name: 'Estados Unidos', code: 'us', dialCode: '1' },
	{ name: 'Estônia', code: 'ee', dialCode: '372' },
	{ name: 'Etiópia', code: 'et', dialCode: '251' },
	{ name: 'Fiji', code: 'fj', dialCode: '679' },
	{ name: 'Filipinas', code: 'ph', dialCode: '63' },
	{ name: 'Finlândia', code: 'fi', dialCode: '358' },
	{ name: 'França', code: 'fr', dialCode: '33' },
	{ name: 'Gabão', code: 'ga', dialCode: '241' },
	{ name: 'Gâmbia', code: 'gm', dialCode: '220' },
	{ name: 'Gana', code: 'gh', dialCode: '233' },
	{ name: 'Geórgia', code: 'ge', dialCode: '995' },
	{ name: 'Gibraltar', code: 'gi', dialCode: '350' },
	{ name: 'Granada', code: 'gd', dialCode: '1-473' },
	{ name: 'Grécia', code: 'gr', dialCode: '30' },
	{ name: 'Guatemala', code: 'gt', dialCode: '502' },
	{ name: 'Guiana', code: 'gy', dialCode: '592' },
	{ name: 'Guiné', code: 'gn', dialCode: '224' },
	{ name: 'Guiné-Bissau', code: 'gw', dialCode: '245' },
	{ name: 'Gâmbia', code: 'gm', dialCode: '220' },
	{ name: 'Guiné Equatorial', code: 'gq', dialCode: '240' },
	{ name: 'Haiti', code: 'ht', dialCode: '509' },
	{ name: 'Honduras', code: 'hn', dialCode: '504' },
	{ name: 'Hong Kong', code: 'hk', dialCode: '852' },
	{ name: 'Hungria', code: 'hu', dialCode: '36' },
	{ name: 'Iémen', code: 'ye', dialCode: '967' },
	{ name: 'Ilhas Cayman', code: 'ky', dialCode: '1-345' },
	{ name: 'Ilhas Cook', code: 'ck', dialCode: '682' },
	{ name: 'Ilhas Malvinas', code: 'fk', dialCode: '500' },
	{ name: 'Ilhas Marshall', code: 'mh', dialCode: '692' },
	{ name: 'Ilhas Salomão', code: 'sb', dialCode: '677' },
	{ name: 'Índia', code: 'in', dialCode: '91' },
	{ name: 'Indonésia', code: 'id', dialCode: '62' },
	{ name: 'Irã', code: 'ir', dialCode: '98' },
	{ name: 'Iraque', code: 'iq', dialCode: '964' },
	{ name: 'Irlanda', code: 'ie', dialCode: '353' },
	{ name: 'Islândia', code: 'is', dialCode: '354' },
	{ name: 'Israel', code: 'il', dialCode: '972' },
	{ name: 'Itália', code: 'it', dialCode: '39' },
	{ name: 'Jamaica', code: 'jm', dialCode: '1-876' },
	{ name: 'Japão', code: 'jp', dialCode: '81' },
	{ name: 'Jordânia', code: 'jo', dialCode: '962' },
	{ name: 'Kiribati', code: 'ki', dialCode: '686' },
	{ name: 'Kuwait', code: 'kw', dialCode: '965' },
	{ name: 'Laos', code: 'la', dialCode: '856' },
	{ name: 'Lesoto', code: 'ls', dialCode: '266' },
	{ name: 'Letônia', code: 'lv', dialCode: '371' },
	{ name: 'Libéria', code: 'lr', dialCode: '231' },
	{ name: 'Libéria', code: 'ly', dialCode: '218' },
	{ name: 'Liechtenstein', code: 'li', dialCode: '423' },
	{ name: 'Lituânia', code: 'lt', dialCode: '370' },
	{ name: 'Luxemburgo', code: 'lu', dialCode: '352' },
	{ name: 'Macau', code: 'mo', dialCode: '853' },
	{ name: 'Madagascar', code: 'mg', dialCode: '261' },
	{ name: 'Malásia', code: 'my', dialCode: '60' },
	{ name: 'Malawi', code: 'mw', dialCode: '265' },
	{ name: 'Maldivas', code: 'mv', dialCode: '960' },
	{ name: 'Mali', code: 'ml', dialCode: '223' },
	{ name: 'Malta', code: 'mt', dialCode: '356' },
	{ name: 'Marianas do Norte', code: 'mp', dialCode: '1-670' },
	{ name: 'Marrocos', code: 'ma', dialCode: '212' },
	{ name: 'Martinica', code: 'mq', dialCode: '596' },
	{ name: 'Maurícia', code: 'mu', dialCode: '230' },
	{ name: 'Mauritânia', code: 'mr', dialCode: '222' },
	{ name: 'México', code: 'mx', dialCode: '52' },
	{ name: 'Moçambique', code: 'mz', dialCode: '258' },
	{ name: 'Moldávia', code: 'md', dialCode: '373' },
	{ name: 'Mônaco', code: 'mc', dialCode: '377' },
	{ name: 'Montenegro', code: 'me', dialCode: '382' },
	{ name: 'Montserrat', code: 'ms', dialCode: '1-664' },
	{ name: 'Namíbia', code: 'na', dialCode: '264' },
	{ name: 'Nauru', code: 'nr', dialCode: '674' },
	{ name: 'Nepal', code: 'np', dialCode: '977' },
	{ name: 'Nicarágua', code: 'ni', dialCode: '505' },
	{ name: 'Níger', code: 'ne', dialCode: '227' },
	{ name: 'Nigéria', code: 'ng', dialCode: '234' },
	{ name: 'Niue', code: 'nu', dialCode: '683' },
	{ name: 'Noruega', code: 'no', dialCode: '47' },
	{ name: 'Nova Caledônia', code: 'nc', dialCode: '687' },
	{ name: 'Nova Zelândia', code: 'nz', dialCode: '64' },
	{ name: 'Níger', code: 'ne', dialCode: '227' },
	{ name: 'Omã', code: 'om', dialCode: '968' },
	{ name: 'Palau', code: 'pw', dialCode: '680' },
	{ name: 'Panamá', code: 'pa', dialCode: '507' },
	{ name: 'Papua-Nova Guiné', code: 'pg', dialCode: '675' },
	{ name: 'Paquistão', code: 'pk', dialCode: '92' },
	{ name: 'Paraguai', code: 'py', dialCode: '595' },
	{ name: 'Peru', code: 'pe', dialCode: '51' },
	{ name: 'Polônia', code: 'pl', dialCode: '48' },
	{ name: 'Portugal', code: 'pt', dialCode: '351' },
	{ name: 'Porto Rico', code: 'pr', dialCode: '1-787' },
	{ name: 'Quênia', code: 'ke', dialCode: '254' },
	{ name: 'Quirguistão', code: 'kg', dialCode: '996' },
	{ name: 'Reino Unido', code: 'gb', dialCode: '44' },
	{ name: 'República Dominicana', code: 'do', dialCode: '1-809' },
	{ name: 'República Tcheca', code: 'cz', dialCode: '420' },
	{ name: 'Reunião', code: 're', dialCode: '262' },
	{ name: 'Ruanda', code: 'rw', dialCode: '250' },
	{ name: 'Rússia', code: 'ru', dialCode: '7' },
	{ name: 'Samoa', code: 'ws', dialCode: '685' },
	{ name: 'San Marino', code: 'sm', dialCode: '378' },
	{ name: 'Santa Helena', code: 'sh', dialCode: '290' },
	{ name: 'São Cristóvão e Nevis', code: 'kn', dialCode: '1-869' },
	{ name: 'São Tomé e Príncipe', code: 'st', dialCode: '239' },
	{ name: 'São Vicente e Granadinas', code: 'vc', dialCode: '1-784' },
	{ name: 'Senegal', code: 'sn', dialCode: '221' },
	{ name: 'Serra Leoa', code: 'sl', dialCode: '232' },
	{ name: 'Seychelles', code: 'sc', dialCode: '248' },
	{ name: 'Singapura', code: 'sg', dialCode: '65' },
	{ name: 'Somália', code: 'so', dialCode: '252' },
	{ name: 'Sri Lanka', code: 'lk', dialCode: '94' },
	{ name: 'Sudão', code: 'sd', dialCode: '249' },
	{ name: 'Suriname', code: 'sr', dialCode: '597' },
	{ name: 'Svalbard', code: 'sj', dialCode: '47' },
	{ name: 'Suécia', code: 'se', dialCode: '46' },
	{ name: 'Suíça', code: 'ch', dialCode: '41' },
	{ name: 'Sudão do Sul', code: 'ss', dialCode: '211' },
	{ name: 'Syria', code: 'sy', dialCode: '963' },
	{ name: 'Somália', code: 'so', dialCode: '252' },
	{ name: 'Tadjiquistão', code: 'tj', dialCode: '992' },
	{ name: 'Tailândia', code: 'th', dialCode: '66' },
	{ name: 'Taiwan', code: 'tw', dialCode: '886' },
	{ name: 'Tanzânia', code: 'tz', dialCode: '255' },
	{ name: 'Territórios Britânicos do Oceano Índico', code: 'io', dialCode: '246' },
	{ name: 'Territórios Franceses do Sul', code: 'tf', dialCode: '262' },
	{ name: 'Timor-Leste', code: 'tl', dialCode: '670' },
	{ name: 'Togo', code: 'tg', dialCode: '228' },
	{ name: 'Tonga', code: 'to', dialCode: '676' },
	{ name: 'Trinidad e Tobago', code: 'tt', dialCode: '1-868' },
	{ name: 'Tunísia', code: 'tn', dialCode: '216' },
	{ name: 'Turcomenistão', code: 'tm', dialCode: '993' },
	{ name: 'Turquia', code: 'tr', dialCode: '90' },
	{ name: 'Tuvalu', code: 'tv', dialCode: '688' },
	{ name: 'Uganda', code: 'ug', dialCode: '256' },
	{ name: 'Uruguai', code: 'uy', dialCode: '598' },
	{ name: 'Uzbequistão', code: 'uz', dialCode: '998' },
	{ name: 'Vanuatu', code: 'vu', dialCode: '678' },
	{ name: 'Vaticano', code: 'va', dialCode: '39' },
	{ name: 'Venezuela', code: 've', dialCode: '58' },
	{ name: 'Vietnã', code: 'vn', dialCode: '84' },
	{ name: 'Zâmbia', code: 'zm', dialCode: '260' },
	{ name: 'Zimbábue', code: 'zw', dialCode: '263' },	
  ];
  